# permissions for end users to edit managementclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managementcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubefirst-cluster-operator
    app.kubernetes.io/part-of: kubefirst-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: managementcluster-editor-role
rules:
- apiGroups:
  - cluster.kubefirst.io
  resources:
  - managementclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.kubefirst.io
  resources:
  - managementclusters/status
  verbs:
  - get
